X(AstNodeClass)

X(AstNodeIf)
X(AstNodeForCond)
X(AstNodeForIter)
X(AstNodeBreak)
X(AstNodeContinue)
X(AstNodeReturn)
X(AstNodeTry)
X(AstNodeRaise)

X(AstNodeDecorator)

X(AstNodeFunc)

X(AstNodeLiteralNone)
X(AstNodeLiteralBool)
X(AstNodeLiteralGL)
X(AstNodeLiteralInt)
X(AstNodeLiteralFloat)
X(AstNodeLiteralStr)
X(AstNodeLiteralTuple)
X(AstNodeLiteralList)
X(AstNodeLiteralDict)
X(AstNodeLiteralEllipsis)

X(AstNodeProgram)
X(AstNodeCompound)

X(AstNodeStar)
X(AstNodeDoubleStar)
X(AstNodeOpUnary)
X(AstNodeOpBinary)
X(AstNodeCompare)
X(AstNodeIs)
X(AstNodeAssign)
X(AstNodeCompoundAssign)

X(AstNodeCall)
X(AstNodeIndex)
X(AstNodeAttr)

X(AstNodeIdentifier)
X(AstNodeDel)
X(AstNodeGlobal)
